### ISSUE TITLE
GR issues to address

### ISSUE THREAD

**Issue by heliosdrm** [heliosdrm/GRUtils.jl#11]
Open issues submitted to GR that can be solved in GRUtils:
- [x] confused about the directions of axes in `heatmap` and `imshow` (jheinen/GR.jl#241) [solved in 0.1.0]
- [x] imshow can not draw an image from a file (jheinen/GR.jl#239) [solved in 0.1.0]
- [x] Allow creating and displaying multiple figures (jheinen/GR.jl#232) [solved in 0.1.0]
- [x] savefig does not save compositions of subplots (jheinen/GR.jl#222) [solved in 0.1.0]
- [x] Hold functionality still does not work in Atom (jheinen/GR.jl#70, jheinen/GR.jl#206) [solved in 0.1.0]
- [x] scatter3 marker size (jheinen/GR.jl#204) [solved in #23]
- [x] Error bar plot (jheinen/GR.jl#194) [solved in #25]
